name: Auto-Async

on:
  push:
    branches: [main]
    tags-ignore: ['*']
  schedule:
    #自动同步：每天早上1点
    - cron:  0 17 * * *
  watch:
    types: [started]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        run: |
          git config --global user.name 'laosan-xx'
          git config --global user.email 'xxhy1989@gmail.com'
          git pull --unshallow
          git remote add upstream https://github.com/fatedier/frp.git
          git fetch upstream
          git merge --no-edit upstream/dev
          git push origin main
